### ISSUE TITLE
Mysql version

### ISSUE THREAD

**Issue by deadmantfa** [pgaultier/yii2-oauth2#15]
Hi pgaultier,

I am looking for a mysql version of the same is it in development?

Regards,
Wenceslaus Dsilva

**Comment by pgaultier** [comment]
Hi, well the MySQL version is not in development yet but if want to start it, updating data services should do the trick.
Merge requests are welcome.

**Comment by deadmantfa** [comment]
Sure will try something and send a PR request. Cheers

**Comment by pgaultier** [comment]
Hi there was a pull request which embed mysql support.
If you want you may try it using the branch `devel`
