### ISSUE TITLE
Press update yii2-redis to 2.0.5

### ISSUE THREAD

**Issue by dixonsatit** [pgaultier/yii2-oauth2#3]
in `composer.json` press update yii2-redis packet to `"yiisoft/yii2-redis": "~2.0.0",`

**Comment by pgaultier** [comment]
We cannot update to yii2-redis 2.0.5 because there is a bug when connection is closed.

Please have a look at :
* https://github.com/yiisoft/yii2-redis/issues/57
* https://github.com/yiisoft/yii2-redis/issues/71

As soon as yii2-redis 2.0.6 we will update the composer

**Comment by dixonsatit** [comment]
Thank you @pgaultier  ^^
