### ISSUE TITLE
When click on authorize button then error "Authorization code doesn't exist or is invalid for the client"

### ISSUE THREAD

**Issue by dixonsatit** [pgaultier/yii2-oauth2#5]
create client user
```
./yii oauth2:client/create --name=doh --userId=1 --redirectUri=http://app-frontend.dev:9090/site/auth?authclient=doh
```

create auth client
```php
<?php

namespace frontend\components;

use yii\authclient\OAuth2;
use dektrium\user\clients\ClientInterface;

class DohClient extends OAuth2
{
    public $authUrl = 'https://sso.sathit.me/oauth2/authorize';

    public $tokenUrl = 'https://sso.sathit.me/oauth2/token';

    public $apiBaseUrl = 'https://sso.sathit.me/api/v1';

    protected function defaultName()
    {
        return 'doh';
    }

    protected function defaultTitle()
    {
        return 'DOH';
    }

    protected function defaultViewOptions()
    {
        return [
            'popupWidth' => 800,
            'popupHeight' => 500,
        ];
    }

    protected function initUserAttributes()
    {
        return $this->api('user/info', 'GET');
    }

        /** @inheritdoc */
    public function getEmail()
    {
        return isset($this->getUserAttributes()['email'])
            ? $this->getUserAttributes()['email']
            : null;
    }
    /** @inheritdoc */
    public function getUsername()
    {
        return;
    }
}

```

Use widget AuthChoice.

```php
        <ul>
            <?php $authAuthChoice = AuthChoice::begin([
            //'baseAuthUrl' => ['/user/security/auth'],
            'baseAuthUrl' => ['/site/auth'],
            'popupMode' => true,
            ]); ?>
                <?php foreach ($authAuthChoice->getClients() as $key => $client): ?>
                    <li><?= $authAuthChoice->clientLink($client,ucfirst($key)) ?></li>
                <?php endforeach; ?>
            <?php AuthChoice::end(); ?>
         </ul>
```

when login & click authorize button then error?

![screen shot 2016-12-14 at 22 47 16](https://cloud.githubusercontent.com/assets/1027274/21189326/e6d22e7c-c250-11e6-8e08-6c73791b10d9.png)

![screen shot 2016-12-14 at 21 19 20](https://cloud.githubusercontent.com/assets/1027274/21185417/1fb01b2c-c243-11e6-81e3-f3ec4b244527.png)

Command:

First, redirect the user to the following URL

```
https://sso.sathit.me/oauth2/authorize/index?response_type=code&client_id=f0124396cad6668186643f55deee9f8a6bfc6169&redirect_uri=http://app-frontend.dev:9090
```

response  authorization code in the URL
```
http://app-frontend.dev:9090/?code=fc5427d1fac73e967097d21748fd97702376ccf5
```

requested using the authorization code.
```
curl -u f0124396cad6668186643f55deee9f8a6bfc6169:43298539b024e5b8c73c60601e7c2b1d06c7aca7  https://sso.sathit.me/oauth2/token -d 'grant_type=authorization_code&code=fc5427d1fac73e967097d21748fd97702376ccf5'
```
result
```json
{"error":"invalid_grant","error_description":"Authorization code doesn't exist or is invalid for the client"}
```

**Comment by pgaultier** [comment]
Can you post your config to check ?

**Comment by dixonsatit** [comment]
~~~        'oauth2' => [
            'class' => 'sweelix\oauth2\server\Module',
            'backend' => 'redis',
            'db' => 'redis',
            'identityClass' => 'common\models\OauthUser',
            'enforceState' => false,
            'allowImplicit' => true,
            // 'allowJwtAccesToken' => true,
        ],
~~~

**Comment by dixonsatit** [comment]
<?php
$params = array_merge(
    require(__DIR__ . '/../../common/config/params.php'),
    require(__DIR__ . '/../../common/config/params-local.php'),
    require(__DIR__ . '/params.php'),
    require(__DIR__ . '/params-local.php')
);
return [
    'id' => 'app-sso',
    'basePath' => dirname(__DIR__),
    'controllerNamespace' => 'sso\controllers',
    'bootstrap' => ['log','oauth2'],
    'modules' => [
        'rbac' => 'dektrium\rbac\RbacWebModule',
        'user' => [
            'class' => 'dektrium\user\Module',
            'enableFlashMessages' => false,
            'admins' => ['dixon'],
            'adminPermission' => 'Admin',
            'urlPrefix'=> 'auth',
            'enableRegistration'=> false,
            'modelMap' => [
                'User' => 'common\models\OauthUser',
            ],
        ],
        'oauth2' => [
            'class' => 'sweelix\oauth2\server\Module',
            'backend' => 'redis',
            'db' => 'redis',
            'identityClass' => 'common\models\OauthUser',
            'enforceState' => false,
            'allowImplicit' => true,
            // 'allowJwtAccesToken' => true,
        ],
        'api' => [
            'class' => 'sso\modules\api\Module',
        ],
    ],
    'components' => [
        'request' => [
            'csrfParam' => '_csrf-sso',
            'parsers' => [
                'application/json' => 'yii\web\JsonParser',
            ],
            'enableCsrfValidation' => false,
        ],
        'user' => [
            'class' => 'sweelix\oauth2\server\web\User',
            'identityClass' => 'dektrium\user\models\User',
            'enableAutoLogin' => true,
            'identityCookie' => ['name' => '_identity-sso', 'httpOnly' => true],
        ],
        'session' => [
            // this is the name of the session cookie used for login on the sso
            'name' => 'advanced-sso',
            'class' => 'yii\redis\Session'
        ],
        'cache' => [
            'class' => 'yii\redis\Cache',
            'keyPrefix' => '_sso_'
        ],
        'log' => [
            'traceLevel' => YII_DEBUG ? 3 : 0,
            'targets' => [
                [
                    'class' => 'yii\log\DbTarget',
                    'levels' => ['error', 'warning'],
                ],
            ],
        ],
        'errorHandler' => [
            'errorAction' => 'site/error',
        ],
        'urlManager' => [
            'enablePrettyUrl' => true,
            'showScriptName' => false,
            'rules' => array_merge(
                require(__DIR__ . '/../../common/config/_rulesUser.php'),[
                [
                    'class' => 'yii\rest\UrlRule',
                    'controller' => [
                        'api/v1/user'
                    ],
                    'extraPatterns' => [
                        'GET info' => 'info',
                    ]
                ]
            ])
        ]
    ],
    'params' => $params,
];

**Comment by dixonsatit** [comment]
~~~
<?php
$params = array_merge(
    require(__DIR__ . '/../../common/config/params.php'),
    require(__DIR__ . '/../../common/config/params-local.php'),
    require(__DIR__ . '/params.php'),
    require(__DIR__ . '/params-local.php')
);
return [
    'id' => 'app-sso',
    'basePath' => dirname(__DIR__),
    'controllerNamespace' => 'sso\controllers',
    'bootstrap' => ['log','oauth2'],
    'modules' => [
        'rbac' => 'dektrium\rbac\RbacWebModule',
        'user' => [
            'class' => 'dektrium\user\Module',
            'enableFlashMessages' => false,
            'admins' => ['dixon'],
            'adminPermission' => 'Admin',
            'urlPrefix'=> 'auth',
            'enableRegistration'=> false,
            'modelMap' => [
                'User' => 'common\models\OauthUser',
            ],
        ],
        'oauth2' => [
            'class' => 'sweelix\oauth2\server\Module',
            'backend' => 'redis',
            'db' => 'redis',
            'identityClass' => 'common\models\OauthUser',
            'enforceState' => false,
            'allowImplicit' => true,
            // 'allowJwtAccesToken' => true,
        ],
        'api' => [
            'class' => 'sso\modules\api\Module',
        ],
    ],
    'components' => [
        'request' => [
            'csrfParam' => '_csrf-sso',
            'parsers' => [
                'application/json' => 'yii\web\JsonParser',
            ],
            'enableCsrfValidation' => false,
        ],
        'user' => [
            'class' => 'sweelix\oauth2\server\web\User',
            'identityClass' => 'dektrium\user\models\User',
            'enableAutoLogin' => true,
            'identityCookie' => ['name' => '_identity-sso', 'httpOnly' => true],
        ],
        'session' => [
            // this is the name of the session cookie used for login on the sso
            'name' => 'advanced-sso',
            'class' => 'yii\redis\Session'
        ],
        'cache' => [
            'class' => 'yii\redis\Cache',
            'keyPrefix' => '_sso_'
        ],
        'log' => [
            'traceLevel' => YII_DEBUG ? 3 : 0,
            'targets' => [
                [
                    'class' => 'yii\log\DbTarget',
                    'levels' => ['error', 'warning'],
                ],
            ],
        ],
        'errorHandler' => [
            'errorAction' => 'site/error',
        ],
        'urlManager' => [
            'enablePrettyUrl' => true,
            'showScriptName' => false,
            'rules' => array_merge(
                require(__DIR__ . '/../../common/config/_rulesUser.php'),[
                [
                    'class' => 'yii\rest\UrlRule',
                    'controller' => [
                        'api/v1/user'
                    ],
                    'extraPatterns' => [
                        'GET info' => 'info',
                    ]
                ]
            ])
        ]
    ],
    'params' => $params,
];
~~~

**Comment by pgaultier** [comment]
Well, this is odd, I created a sample here to check it and I am not able to reproduce the bug.

Are you able to create a small app I can download and deploy here to try to reproduce your bug ?

**Comment by dixonsatit** [comment]
Hello. @pgaultier i create sample project at https://github.com/dixonsatit/Yii2-Oauth2-Server-Sample

template config db https://github.com/dixonsatit/Yii2-Oauth2-Server-Sample/blob/master/environments/dev/common/config/main-local.php

PHP: php7-fpm
Redis: redis:3.2.6
User: yii2-user

Thank you. _/\_

**Comment by pgaultier** [comment]
Ok, found the bug ;-) It was because I didn't allow numeric IDs for users... 

you should be able to make it work using `devel` branch. Keep me informed if it's OK for you to create a new release.

Thanks

**Comment by dixonsatit** [comment]
Thank you! @pgaultier
