### ISSUE TITLE
How to get all client from redis?

### ISSUE THREAD

**Issue by dixonsatit** [pgaultier/yii2-oauth2#9]
hi @pgaultier.
I want to get all client by user from redis?

**Comment by dixonsatit** [comment]
Thank you. @pgaultier _/\_

**Comment by pgaultier** [comment]
Hello,

We finally updated the code to let you perform queries : 

* `Client::findAllByUserId()`
* `$client->addUser()`
* `$client->hasUser()`
* `$client->removeUser()`

Everything has been pushed on `devel` branch. Please tell me if it's not working.

Regards

**Comment by pgaultier** [comment]
BTW, additional methods have been created

* `AccessToken::deleteAllByUserId()`
* `AccessToken::deleteAllByClientId()`
* `RefreshToken::deleteAllByUserId()`
* `RefreshToken::deleteAllByClientId()`

We also added automatic expiration of AccessTokens, RefreshTokens and AuthorizationCodes to not fill the database

**Comment by pgaultier** [comment]
Any news ? Can I close the issue ?
